// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
const spec_Name = {__proto__:null,true:86, false:86, skip:100}
export const parser = LRParser.deserialize({
  version: 14,
  states: ")SOYQPOOOeQPO'#C_OyQPO'#C{O!OQPO'#C}OOQO'#Cz'#CzQOQPOOOOQO'#C`'#C`OOQO'#Cf'#CfO!TQPO'#CfO!YQQO'#CrOeQPO'#CmO!nQQO'#D[OOQO'#D['#D[O#YQPO'#DVOeQPO'#CuOOQO'#DW'#DWO#kQPO,58yO#pQPO,59gOOQO,59i,59iOOQO,59Q,59QO#pQPO,59SO#pQPO,59SO#pQPO,59^O$OQQO,59XO$VQPO,59eO$eQPO'#CeOOQO,58|,58|OeQPO,59YOeQPO,59[OeQPO,59cOeQPO'#DPO$yQPO,59qOOQO,59a,59aOOQO1G.e1G.eO%RQQO1G/RO#pQPO'#CmOOQO1G.n1G.nO%xQQO1G.nO&VQSO1G.xOOQO1G.s1G.sOOQO1G/P1G/PO'YQQO'#DYO#pQPO'#DYO'aQPO,59POOQO1G.t1G.tO'fQPO1G.vO'zQPO1G.}O(`QPO,59kOOQO-E6}-E6}OOQO7+$m7+$mO(qQQO,59XO)SQPO'#DOO)eQPO,59tO)mQQO,59tOOQO1G.k1G.kO)tQSO1G.nO*UQQO,59jO#pQPO,59jOOQO-E6|-E6|O*jQPO1G/`O*rQQO1G/UO#pQPO,59S",
  stateData: "+W~OvOSPOS~OTQOxPO!SRO~OTZOWYOZWOj^O{UO!PVO~OpaO~O!RbO~O!PcO~O]dO^dO_dO`eOgfOhfO~OWiO]!OX^!OX_!OX`!OXg!OXh!OXV!OX~OckOelOlmO!QnOwyX~OwqO~OT[OWsOZWO!PVO~OVwO~P!YOVxOckOelOlmO~OT[OWsOZWO}zO!PVOV|P~O!QnOwya~O]dO^dO_dO`eO!R!RO~O]dO^dO_dO`[iV[i!Q[i~Og[ih[i!R[i~P%dO]dO^dO_dO`!_Ocfiefilfiwfi!QfiVfi~O]dO^dO_dO`eO!Q!TO~OV|X~P&wOV!WO~OckOedildiwdi!QdiVdi~OckOelOlmOwki!QkiVki~OckOelOlmOwsa!Qsa~OVwO]dO^dO_dO`eO~OT[OWsOZWO}!ZO!PVO~O!Q!TOV|a~OV|a~P&wOc[ie[il[iw[i~P%dO]dO^dO_dO`eOVra!Qra~O!Q!TOV|i~O]dO^dO_dO`eOVri!Qri~O",
  goto: "$o!PPPP!Q!TP!TPP!^!aP!aPPPP!a!TP!TP!TPP!TP!TP!T!Q!tP!t!w#RPPPPP#X#[P#qP#tRTO__PY^klmnRjZs[PY^adefiklmnsz!T!Z!_RSOQ!UyS![!U!]R!]!VQo]R!QoR`PQ]PQhYQp^Q|kQ}lQ!OmR!PnR{i[XP^klmnQgYQraQtdQueQvfQyiQ!SsQ!VzQ!X!_Q!Y!TR!^!Z",
  nodeNames: "⚠ LineComment TopDecl Assertion LitBool Name PredicateApp ) ( ArgList LitNumber ArithOp BinArithE ArithOp ArithOp ArithOp ArithOp ParenthesizedArithExp AndE AndOp OrE OrOp CompE CompareOp CompareOp NegE NotOp ImpliesE ImpliesOp ParenthesizedFormula Command Assign AssignOp CmdSkip",
  maxTerm: 50,
  nodeProps: [
    ["group", -8,4,6,18,20,22,25,27,29,"Formula"],
    ["openedBy", 7,"("],
    ["closedBy", 8,")"]
  ],
  skippedNodes: [0,1],
  repeatNodeCount: 2,
  tokenData: "'n~RnXY#PYZ#P]^#Ppq#Pqr#bst#ouv$Wvw$]xy$hyz$mz{$r{|$w|}$|}!O%R!O!P%Y!P!Q%k!Q![%p![!]%x!]!^&T!^!_&Y!_!`&g!`!a&Y!c!}&t#R#S&t#T#o&t#o#p'S#p#q'X#q#r'd#r#s'i$r$s'i~#USv~XY#PYZ#P]^#Ppq#PR#gPjP!_!`#jQ#oOgQ~#tSP~OY#oZ;'S#o;'S;=`$Q<%lO#o~$TP;=`<%l#o~$]O^~~$`Pvw$c~$hOc~~$mOW~~$rOV~~$wO_~U$|O`U~%RO!Q~V%YO`UZP~%]P!O!P%`~%cP!O!P%f~%kO}~~%pO]~~%uP!P~!Q![%p~%{P!_!`&O~&TOp~~&YO!R~~&_Ph~!_!`&b~&gOh~V&lPgQ!`!a&oT&tOlT~&yRT~!c!}&t#R#S&t#T#o&t~'XOx~~'[P#p#q'_~'dOe~~'iOw~P'nOjP",
  tokenizers: [0, 1, 2],
  topRules: {"TopDecl":[0,2]},
  dynamicPrecedences: {"18":-1},
  specialized: [{term: 5, get: (value) => spec_Name[value] || -1}],
  tokenPrec: 0
})
