name: Check and deploy to GitHub Pages

on:
  push:
    branches: 'public'

jobs:
  build_site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # If you're using pnpm, add this step then change the commands and cache key below to use `pnpm`
      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Cache pnpm store
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('pnpm-lock.yaml') }}-${{ hashFiles('package.json') }}
          restore-keys: |
            pnpm-store-

      - name: Install Dependencies
        if: steps.cache-pnpm-store.outputs.cache-hit != 'true'
        run: |
          pnpm install --frozen-lockfile

      - name: Check
        run: pnpm run check
        # TODO: Add lint after sorting out Prettier config

      - name: Test
        run: pnpm run test

      - name: Build
        env:
            BASE_PATH: '/${{ github.event.repository.name }}'
        run: pnpm run build

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          # this should match the `pages` option in your adapter-static options
          path: 'build/'

  deploy:
    needs: build_site
    runs-on: ubuntu-latest
    if: github.event.repository.private == false

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
